// Liste étendue des principales villes canadiennes
export const canadianCities = [
  { value: "toronto", label: "Toronto" },
  { value: "montreal", label: "Montréal" },
  { value: "vancouver", label: "Vancouver" },
  { value: "calgary", label: "Calgary" },
  { value: "edmonton", label: "Edmonton" },
  { value: "ottawa", label: "Ottawa" },
  { value: "quebec", label: "Québec" },
  { value: "winnipeg", label: "Winnipeg" },
  { value: "hamilton", label: "Hamilton" },
  { value: "kitchener", label: "Kitchener" },
  { value: "london", label: "London" },
  { value: "victoria", label: "Victoria" },
  { value: "halifax", label: "Halifax" },
  { value: "oshawa", label: "Oshawa" },
  { value: "gatineau", label: "Gatineau" },
  { value: "saskatoon", label: "Saskatoon" },
  { value: "regina", label: "Regina" },
  { value: "sherbrooke", label: "Sherbrooke" },
  { value: "kelowna", label: "Kelowna" },
  { value: "barrie", label: "Barrie" },
  { value: "st-johns", label: "St. John's" },
  { value: "sudbury", label: "Sudbury" },
  { value: "windsor", label: "Windsor" },
  { value: "moncton", label: "Moncton" },
  { value: "trois-rivieres", label: "Trois-Rivières" },
  { value: "saguenay", label: "Saguenay" },
  { value: "charlottetown", label: "Charlottetown" },
  { value: "fredericton", label: "Fredericton" },
  { value: "prince-george", label: "Prince George" },
  { value: "red-deer", label: "Red Deer" },
  { value: "lethbridge", label: "Lethbridge" },
  { value: "kamloops", label: "Kamloops" },
  { value: "drummondville", label: "Drummondville" },
  { value: "thunder-bay", label: "Thunder Bay" },
  { value: "brampton", label: "Brampton" },
  { value: "mississauga", label: "Mississauga" },
  { value: "markham", label: "Markham" },
  { value: "surrey", label: "Surrey" },
  { value: "burnaby", label: "Burnaby" },
  { value: "longueuil", label: "Longueuil" },
];
